// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN0KRrBRs7EJqig_q1YARJNkc2nQEzT3Y',
    appId: '1:439799537108:web:f8129cba9c7b46c09a8a41',
    messagingSenderId: '439799537108',
    projectId: 'summerhackathon-d2525',
    authDomain: 'summerhackathon-d2525.firebaseapp.com',
    databaseURL: 'https://summerhackathon-d2525-default-rtdb.firebaseio.com',
    storageBucket: 'summerhackathon-d2525.appspot.com',
    measurementId: 'G-9WM5RFN9D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZvCY3tj3Et7qRnsLtcYWyj9Kz8P1kuwc',
    appId: '1:439799537108:android:686a23d4e3ee626c9a8a41',
    messagingSenderId: '439799537108',
    projectId: 'summerhackathon-d2525',
    databaseURL: 'https://summerhackathon-d2525-default-rtdb.firebaseio.com',
    storageBucket: 'summerhackathon-d2525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvKd9XWATMalj12uUUBv4FatngusMXr8Q',
    appId: '1:439799537108:ios:5ca57ce424de30e89a8a41',
    messagingSenderId: '439799537108',
    projectId: 'summerhackathon-d2525',
    databaseURL: 'https://summerhackathon-d2525-default-rtdb.firebaseio.com',
    storageBucket: 'summerhackathon-d2525.appspot.com',
    iosClientId: '439799537108-n7ka0atv33qu6tto5nhrujk35dna8inc.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamAProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvKd9XWATMalj12uUUBv4FatngusMXr8Q',
    appId: '1:439799537108:ios:d2ceefc264050fba9a8a41',
    messagingSenderId: '439799537108',
    projectId: 'summerhackathon-d2525',
    databaseURL: 'https://summerhackathon-d2525-default-rtdb.firebaseio.com',
    storageBucket: 'summerhackathon-d2525.appspot.com',
    iosClientId: '439799537108-o54ms1qj0pn3p5nmv8ndgmmcsr9231pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamAProject.RunnerTests',
  );
}
